apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore-webapi-sample
  labels:
    app: aspnetcore-webapi-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetcore-webapi-sample
  template:
    metadata:
      labels:
        app: aspnetcore-webapi-sample
    spec:
      containers:
      - name: aspnetcore-webapi
        image: igorbrilo/aspnetcore-webapi-sample:v2.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetcore-webapi-sample
spec:
  selector:
    app: aspnetcore-webapi-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
